<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="BlazeHotelSystem.Admin" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
</head>
<body>
    <form id="form1" runat="server">
        <div style="display:flex;">
            
            <div class="sidebar">
                <div class="LOGO">BLAZE</div>
                <div><i class="fas fa-tachometer-alt"></i>Dashboard</div>
                <div><i class="fas fa-users"></i>Customers</div>
                <div><i class="fas fa-book"></i>Booking</div>
                <div><i class="fas fa-comment-dots"></i>Feedback</div>
                <div><span class="material-symbols-outlined">logout</span>logout</div>

            </div>
            <!--content-->
            <div class="items">
                
                <div >
                    <h2>Customers</h2>
                  <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="True" AutoGenerateDeleteButton="False" AutoGenerateEditButton="False" BorderStyle="None" CellSpacing="10" EmptyDataText="Empty" EnableSortingAndPagingCallbacks="True" ForeColor="Black" GridLines="None" HorizontalAlign="Center" Width="300px" AllowPaging="True" AllowCustomPaging="False" OnRowDeleting="GridView3_RowDeleting" >
                      <Columns>
                          <asp:ButtonField Text="Delete" CommandName="Delete" ItemStyle-BackColor="Red" ItemStyle-ForeColor="White" />
                      </Columns>
                  </asp:GridView>
                 </div>

                 <div >
                     <h2>Booking</h2>
                  <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="True" AutoGenerateDeleteButton="False" AutoGenerateEditButton="False" BorderStyle="None" CellSpacing="10" EmptyDataText="Empty" EnableSortingAndPagingCallbacks="True" ForeColor="Black" GridLines="None" HorizontalAlign="Center" Width="300px" OnRowDeleting="GridView2_RowDeleting">
                      <Columns>
                          <asp:ButtonField Text="Edit" CommandName="Edit" ItemStyle-BackColor="SeaGreen" ItemStyle-ForeColor="White" />   
                      </Columns>
                       </asp:GridView>
                 </div>

                 <div style="text-align:left">
                     <h2>Contacts</h2>
                  <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="True" BorderStyle="None" CellSpacing="2" EmptyDataText="Empty" EnableSortingAndPagingCallbacks="True" ForeColor="Black" GridLines="None" HorizontalAlign="Center" Width="300px" CellPadding="10" OnRowDeleting="GridView1_RowDeleting" >
                      <Columns>
                        <asp:ButtonField Text="Edit" CommandName="Edit" ItemStyle-BackColor="SeaGreen" ItemStyle-ForeColor="White" />
                      </Columns>

                  </asp:GridView>
                 </div>

            </div>
            
        </div>
    </form>
</body>
</html>
<style>
    body{
        background-color:lightgray;
    }
    .LOGO{
        text-align:center;
        margin-top:30px;
        font-size: 30px;
        color:orangered;
    }
    .sidebar{
        display:flex;
        flex-direction:column;
        align-items:center;
        justify-content:space-around;
        position:absolute;
        left:30px;
        top:10px;
        bottom:10px;
        background-color:white;
        width:250px;
        border-radius:15px;
    }
    .sidebar >div{
        width:200px;
        height:40px;
        text-align:center;
        padding-top:20px;
        border-radius:10px;
    }
    .sidebar >div:hover{
        background-color:seagreen;
        transition:ease-in-out .5s;
    }
    .sidebar ul{
        margin-top:30%;
        list-style:none;
        left:0;
        background-color:lightblue;
        text-align:left;
    }
    li{
        left:0;
        text-align:center;
        font-size:18px;
        margin:30px;
        padding-top:15px;
    }
    li:hover{
        text-decoration:underline;
        color:seagreen;
        background-color:lightgray;
        transition:ease-in-out .5s;

    }
    h2{
        text-align:center;
        text-decoration:underline;
    }
    .items{
        width:700px;
        background-color:white;
        border-radius: 15px;
        text-align:left;
        position:relative;
        margin-left:30%;
        display:flex;
        flex-direction:column;
    }
</style>
